import type { Metadata } from "next";
import { MuseoModerno , Montserrat, Playfair_Display} from 'next/font/google'
// import "./globals.css";
import Nav from "@/components/Navbar";
import Footer from "@/components/Footer";
import ScrollToTopButton from "@/components/UpButton";

const museomoderno= MuseoModerno({
  subsets:["latin"],
})
const montserrat= Montserrat({
  subsets:["latin"],
})


const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${museomoderno.className} ${montserrat.className} ${playfairDisplay.className} antialiased`}
      >
      {children}
      </body>
    </html>
  );
}
